Improved container init, display output by using docker logs and automatically exit when init is completed

diff --git a/bin/tugger b/bin/tugger
--- a/bin/tugger
+++ b/bin/tugger
@@ -199,26 +199,29 @@ fi
 # force recreate of berksfile lock
 if [ "$recreate_berksfile_lock" == 1 ]
 then
-    touch $HOME/.tugger/projects/$project_name/recreate_berksfile_lock.touch
+    touch $HOME/.tugger/projects/$project_name/recreate-berksfile-lock.touch
 else
-    rm -f $HOME/.tugger/projects/$project_name/recreate_berksfile_lock.touch
+    rm -f $HOME/.tugger/projects/$project_name/recreate-berksfile-lock.touch
 fi
 
 # force to run fresh provisioning when recreating a new container7
 if [ "$recreate_container" == 1 ]
 then
-    rm -f $HOME/.tugger/projects/$project_name/chef_completed.touch
+    rm -f $HOME/.tugger/projects/$project_name/chef-completed.touch
 fi
 
 # get status information
-existing_container_id="$(docker inspect --format '{{.Id}}' "$project_name" 2> /dev/null || true)"
-existing_container_running="$(docker inspect --format '{{.State.Running}}' "$project_name" 2> /dev/null || true)"
-existing_container_ip_address="$(docker inspect --format '{{.NetworkSettings.IPAddress}}' "$project_name" 2> /dev/null || true)"
-existing_container_ip_address_display="$existing_container_ip_address"
-if [ "$existing_container_ip_address_display" == "" ]
-then
-    existing_container_ip_address_display="-"
-fi
+get_container_status() {
+    export existing_container_id="$(docker inspect --format '{{.Id}}' "$project_name" 2> /dev/null || true)"
+    export existing_container_running="$(docker inspect --format '{{.State.Running}}' "$project_name" 2> /dev/null || true)"
+    export existing_container_ip_address="$(docker inspect --format '{{.NetworkSettings.IPAddress}}' "$project_name" 2> /dev/null || true)"
+    export existing_container_ip_address_display="$existing_container_ip_address"
+    if [ "$existing_container_ip_address_display" == "" ]
+    then
+        export existing_container_ip_address_display="-"
+    fi
+}
+get_container_status
 
 # handle the requested tugger action
 if [ "$tugger_action" == "remove" ]
@@ -238,23 +241,42 @@ then
 fi
 if [ "$tugger_action" == "start" ] || [ "$tugger_action" == "restart" ]
 then
+    # start or create container
+    rm -f $HOME/.tugger/projects/$project_name/init-completed.touch
     if [ "$existing_container_id" != "" ] && [ "$recreate_container" == 1 ]
     then
         echo "Recreate option given, deleting existing container '$project_name'..."
-        docker rm "$project_name"
+        docker rm "$project_name" > /dev/null
         existing_container_id=""
     fi
     if [ "$existing_container_id" == "" ]
     then
         echo "Creating new container '$project_name'..."
-        docker run --name "$project_name" --hostname "$project_name" -v $HOME/.ssh/:/home/webserver/.ssh/ -v $HOME/.gitconfig:/home/webserver/.gitconfig -v $HOME/.tugger/projects/$project_name:/tugger -v $tugger_install_dir/lib:/tugger/lib -v $project_dir:/var/www/webproject -t "$tugger_stack_shared_image_name" /bin/bash /tugger/lib/tugger-container-init/init-wrapper
+        docker run -d --name "$project_name" --hostname "$project_name" -v $HOME/.ssh/:/home/webserver/.ssh/ -v $HOME/.gitconfig:/home/webserver/.gitconfig -v $HOME/.tugger/projects/$project_name:/tugger -v $tugger_install_dir/lib:/tugger/lib -v $project_dir:/var/www/webproject -t "$tugger_stack_shared_image_name" /bin/bash /tugger/lib/tugger-container-init/init-wrapper > /dev/null
     else
         echo "Starting already existing container '$project_name'..."
-        docker start -i "$project_name"
+        docker start "$project_name" > /dev/null
     fi
+    # get log output
+    sleep 5
+    docker logs --tail="all" -f "$project_name" &
+    docker_logs_pid=$!
+    # wait until init completed
+    while ! test -e $HOME/.tugger/projects/$project_name/init-completed.touch
+    do
+        sleep 2
+        if [ "$(docker inspect --format '{{.State.Running}}' "$project_name" 2> /dev/null || true)" != "true" ]
+        then
+            echo "Container not running anymore, container init failed?"
+            exit 1
+        fi
+    done
+    echo "Container init completed"
+    kill -PIPE "$docker_logs_pid"
 fi
-if [ "$tugger_action" == "status" ]
+if [ "$tugger_action" == "status" ] || [ "$tugger_action" == "start" ] || [ "$tugger_action" == "restart" ]
 then
+    get_container_status
     echo "Status information for container:     $project_name"
     if [ "$existing_container_id" == "" ]
     then
