Implement init wrapper script to handle provisioning and calling the tugger-stack's real init script

diff --git a/bin/tugger b/bin/tugger
--- a/bin/tugger
+++ b/bin/tugger
@@ -3,6 +3,9 @@
 # exit on error
 set -e
 
+# get real path of tugger installation, also if started from symlink
+tugger_install_dir="$(dirname "$(dirname "$(realpath "$0")")")"
+
 # check if running on mac
 running_on_mac=0
 if [ "$(uname)" == "Darwin" ]
@@ -20,6 +23,7 @@ fi
 # parse command line args
 show_help=0
 reprovision=0
+recreate_berksfile_lock=0
 rebuild_image=0
 tugger_action=""
 tugger_file="./Tuggerfile"
@@ -34,6 +38,9 @@ do
         ;;
     -r|--reprovision)
         reprovision=1
+        ;;
+    -l|--recreate-berksfile-lock)
+        recreate_berksfile_lock=1
         ;;
     -b|--rebuild-image)
         rebuild_image=1
@@ -81,6 +88,8 @@ then
     echo "  -h, --help                      Show this help"
     echo "  -r, --reprovision               Force to run provisioning, also when caontainer was"
     echo "                                  already provisioned before"
+    echo "  -l, --recreate-berksfile-lock   Force to recreate Berksfile.lock and update the used"
+    echo "                                  versions of the packages"
     echo "  -b, --rebuild-image             Force to rebuild the docker image, also when image"
     echo "                                  was already build from Dockerfile before"
     echo "  -f, --file DOCKERUP_FILE        Pass path to 'Tuggerfile' to be used, default is"
@@ -163,6 +172,41 @@ then
     docker build $docker_build_params -t "$tugger_stack_shared_image_name" "$HOME/.tugger/projects/$project_name/tugger-stack"
 fi
 
-# todo: run container with init-wrapper-script
-# the init-wrapper-script should a) run provisioning if first run or --reprovision given and b) run init.sh from tugger-stack
+# reprovision
+if [ "$reprovision" == 1 ]
+then
+    touch $HOME/.tugger/projects/$project_name/reprovision.touch
+else
+    rm -f $HOME/.tugger/projects/$project_name/reprovision.touch
+fi
 
+# force recreate of berksfile lock
+if [ "$recreate_berksfile_lock" == 1 ]
+then
+    touch $HOME/.tugger/projects/$project_name/recreate_berksfile_lock.touch
+else
+    rm -f $HOME/.tugger/projects/$project_name/recreate_berksfile_lock.touch
+fi
+
+# create docker container
+existing_container_id="$(docker inspect --format '{{.Id}}' "$project_name" 2> /dev/null || true)"
+if [ "$tugger_action" == "stop" ] || [ "$tugger_action" == "restart" ]
+then
+    echo "Stopping container '$project_name'..."
+    docker stop "$project_name"
+elif [ "$tugger_action" == "start" ] || [ "$tugger_action" == "restart" ]
+then
+    if [ "$existing_container_id" == "" ]
+    then
+        echo "Creating new container '$project_name'..."
+        docker run --name "$project_name" --hostname "$project_name" -v $HOME/.ssh/:/home/webserver/.ssh/ -v $HOME/.gitconfig:/home/webserver/.gitconfig -v $HOME/.tugger/projects/$project_name:/tugger -v $tugger_install_dir/lib:/tugger/lib -v $(dirname $(pwd)):/var/www/webproject -t "$tugger_stack_shared_image_name" /bin/bash /tugger/lib/tugger-container-init/init-wrapper
+    else
+        echo "Starting already existing container '$project_name'..."
+        docker start -i "$project_name"
+    fi
+elif [ "$tugger_action" == "status" ]
+then
+    echo "tugger status not implemented yet"
+else
+    echo "invalid action given: '$tugger_action'"
+fi
