Implemented automatic update of /etc/hosts and fixed bug, do not allow to start when already running

diff --git a/bin/tugger b/bin/tugger
--- a/bin/tugger
+++ b/bin/tugger
@@ -245,10 +245,13 @@ set_container_status_vars() {
     export existing_container_id="$(docker inspect --format '{{.Id}}' "$project_name" 2> /dev/null || true)"
     export existing_container_running="$(docker inspect --format '{{.State.Running}}' "$project_name" 2> /dev/null || true)"
     export existing_container_ip_address="$(docker inspect --format '{{.NetworkSettings.IPAddress}}' "$project_name" 2> /dev/null || true)"
-    export existing_container_ip_address_display="$existing_container_ip_address"
-    if [ "$existing_container_ip_address_display" == "" ]
+    if [ "$existing_container_ip_address" != "" ]
     then
+        export existing_container_ip_address_display="$existing_container_ip_address"
+        export existing_container_etc_hosts_display="$(([ "$etc_hosts" != "" ] && echo "$etc_hosts") || echo "-")"
+    else
         export existing_container_ip_address_display="-"
+        export existing_container_etc_hosts_display="-"
     fi
     export docker_host_ip="127.0.0.1"
     if [ "$running_on_mac" == 1 ]
@@ -262,7 +265,7 @@ set_container_status_vars
 is_port_used() {
     p="$1"
     # check against tugger ports
-    tugger_ports_output="$(cat "$HOME/.tugger/ports" 2> /dev/null | awk "\$3 == \"$p\"")"
+    ports_output="$(cat "$HOME/.tugger/ports" 2> /dev/null | awk "\$3 == \"$p\"")"
     # netstat check
     netstat_output=""
     if [ "$running_on_mac" != 1 ]
@@ -271,7 +274,7 @@ is_port_used() {
     else
         netstat_output="$(netstat -anp tcp | awk "\$6 == \"LISTEN\" && \$4 ~ \"\\\\.$p\"")"
     fi
-    if [ "$netstat_output" != "" ] || [ "$tugger_ports_output" != "" ]
+    if [ "$netstat_output" != "" ] || [ "$ports_output" != "" ]
     then
         # return 0 == success
         return 0
@@ -293,17 +296,17 @@ gen_host_port() {
     echo "72$[$p % 100]"
 }
 get_mapped_ports() {
-    for container_port in $tugger_ports
+    for container_port in $mapped_ports
     do
-        tugger_ports_output="$(cat "$HOME/.tugger/ports" 2> /dev/null | awk "\$1 == \"$project_name\" && \$2 == \"$container_port\"")"
-        if [ "$tugger_ports_output" == "" ]
+        ports_output="$(cat "$HOME/.tugger/ports" 2> /dev/null | awk "\$1 == \"$project_name\" && \$2 == \"$container_port\"")"
+        if [ "$ports_output" == "" ]
         then
             host_port="$(find_free_port $(gen_host_port $container_port))"
             echo "$project_name $container_port $host_port" >> "$HOME/.tugger/ports"
         fi
     done
-    tugger_ports_output_full="$(cat "$HOME/.tugger/ports" 2> /dev/null | awk "\$1 == \"$project_name\"")"
-    echo "$tugger_ports_output_full"
+    ports_output_full="$(cat "$HOME/.tugger/ports" 2> /dev/null | awk "\$1 == \"$project_name\"")"
+    echo "$ports_output_full"
 }
 get_mapped_ports_params() {
     map="$1"
@@ -325,6 +328,7 @@ then
     echo "Permanently removing container '$project_name'..."
     docker rm "$project_name" > /dev/null
 fi
+# stop container?
 if [ "$tugger_action" == "stop" ] || [ "$tugger_action" == "restart" ]
 then
     echo "Stopping container '$project_name'..."
@@ -334,11 +338,23 @@ then
         exit 1
     fi
     docker stop "$project_name" > /dev/null
+    sleep 2
+    # update status
+    set_container_status_vars
 fi
+# start container?
 if [ "$tugger_action" == "start" ] || [ "$tugger_action" == "restart" ]
 then
     # start or create container
+    if [ "$existing_container_running" == "true" ]
+    then
+        echo "Failed to start container, container is already running"
+        exit 1
+    fi
     rm -f "$HOME/.tugger/projects/$project_name/init-completed.touch"
+    echo -n > "$HOME/.tugger/projects/$project_name/init.log"
+    tail -f "$HOME/.tugger/projects/$project_name/init.log" &
+    log_tail_pid=$!
     if [ "$existing_container_id" != "" ] && [ "$recreate_container" == 1 ]
     then
         echo "Recreate option given, deleting existing container '$project_name'..."
@@ -353,10 +369,6 @@ then
         echo "Starting already existing container '$project_name'..."
         docker start "$project_name" > /dev/null
     fi
-    # get log output
-    sleep 5
-    docker logs --tail="all" -f "$project_name" &
-    docker_logs_pid=$!
     # wait until init completed
     while ! test -e "$HOME/.tugger/projects/$project_name/init-completed.touch"
     do
@@ -364,15 +376,79 @@ then
         if [ "$(docker inspect --format '{{.State.Running}}' "$project_name" 2> /dev/null || true)" != "true" ]
         then
             echo "Container not running anymore, container init failed?"
+            kill -PIPE "$log_tail_pid"
             exit 1
         fi
     done
     echo "Container init completed"
-    kill -PIPE "$docker_logs_pid"
+    echo
+    kill -PIPE "$log_tail_pid"
+    # update status
+    set_container_status_vars
 fi
+# update /etc/hosts?
+if [ "$etc_hosts" != "" ] && ([ "$tugger_action" == "start" ] || [ "$tugger_action" == "restart" ] || [ "$tugger_action" == "remove" ])
+then
+    echo "Updating /etc/hosts file..."
+    etc_hosts_ip="$(([ "$running_on_mac" != 1 ] && echo "$existing_container_ip_address") || (echo "$docker_host_ip"))"
+    # remove invalid hosts entries
+    remove_ips_and_hosts=""
+    hosts_output="$(cat "/etc/hosts" 2> /dev/null | awk "\$3 == \"#\" && \$4 == \"added-by-tugger(project_name=$project_name)\" { print \$1\":\"\$2 }")"
+    for ip_and_host in $hosts_output
+    do
+        ip="$(echo "$ip_and_host" | cut -d ":" -f 1)"
+        host="$(echo "$ip_and_host" | cut -d ":" -f 2)"
+        if [ "$tugger_action" == "remove" ] || [ "$ip" != "$etc_hosts_ip" ]
+        then
+            remove_ips_and_hosts="$remove_ips_and_hosts $ip_and_host"
+            continue
+        fi
+        host_valid=0
+        for h in $etc_hosts
+        do
+            if [ "$host" == "$h" ]
+            then
+                host_valid=1
+                break
+            fi
+        done
+        if [ "$host_valid" != 1 ]
+        then
+            remove_ips_and_hosts="$remove_ips_and_hosts $ip_and_host"
+            continue
+        fi
+    done
+    for ip_and_host in $remove_ips_and_hosts
+    do
+        ip="$(echo "$ip_and_host" | cut -d ":" -f 1)"
+        host="$(echo "$ip_and_host" | cut -d ":" -f 2)"
+        ip_escaped="$(echo "$ip" | sed 's/\./\\\./g')"
+        host_escaped="$(echo "$host" | sed 's/\./\\\./g')"
+        echo "Removing $ip $host from /etc/hosts... (please enter password for sudo operation when prompted)"
+        sudo sed -i "/$ip_escaped $host_escaped # added-by-tugger(project_name=$project_name)/d" /etc/hosts
+    done
+    # add missing hosts entries
+    if [ "$tugger_action" == "start" ] || [ "$tugger_action" == "restart" ]
+    then
+        add_hosts=""
+        for host in $etc_hosts
+        do
+            hosts_output="$(cat "/etc/hosts" 2> /dev/null | awk "\$1 == \"$etc_hosts_ip\" && \$2 == \"$host\" && \$3 == \"#\" && \$4 == \"added-by-tugger(project_name=$project_name)\"")"
+            if [ "$hosts_output" == "" ]
+            then
+                add_hosts="$add_hosts $host"
+            fi
+        done
+        for host in $add_hosts
+        do
+            echo "Adding $etc_hosts_ip $host to /etc/hosts... (please enter password for sudo operation when prompted)"
+            echo "$etc_hosts_ip $host # added-by-tugger(project_name=$project_name)" | sudo tee -a /etc/hosts > /dev/null
+        done
+    fi
+fi
+# output status?
 if [ "$tugger_action" == "status" ] || [ "$tugger_action" == "start" ] || [ "$tugger_action" == "restart" ]
 then
-    set_container_status_vars
     echo
     echo "Status information for container:     $project_name"
     if [ "$existing_container_id" == "" ]
@@ -382,6 +458,7 @@ then
         echo "Container ID:                         $existing_container_id"
         echo "Container currently running:          $existing_container_running"
         echo "Current container IP address:         $existing_container_ip_address_display"
+        echo "Current container host name(s):       $existing_container_etc_hosts_display"
         echo
         echo "Mapped ports:"
         echo "$mapped_ports_summary";
